# Generated by Django 4.2.2 on 2024-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="comments",
            field=models.TextField(
                blank=True, help_text="коментарии", null=True, verbose_name="Comments"
            ),
        ),
    ]
