# Generated by Django 4.2.2 on 2024-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок блога",
                        max_length=50,
                        verbose_name="Заголовок блога",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержание блога",
                        null=True,
                        verbose_name="Содержание блога",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blog/blog_preview",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Введите дату создания блога",
                        null=True,
                        verbose_name="Дата создания блога",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="просмотры"),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
